(let (source https://emacstragic.net/2013/03/03/project-euler-no-1-in-emacs-elisp/))
(defun divisibleby (dividend divisor)
  "check if dividend is divisible by divisor"
  (if (not(integerp dividend))
      (error "dividend must be an integer"))
    (if (not(integerp divisor))
        (error "divisor must be an integer"))
    (zerop (mod dividend divisor))
    )

  (let ((lower 1)
        (upper 1000)
        (sum 0))
    (loop for i from lower to (- upper 1) do (if (or (divisibleby i 3)
                                                     (divisibleby i 5))
                                                 (setq sum (+ sum i)))
          )
    (message "sum is: %d" sum)
    )
